version: '3'
services:
#Laravel App
    app:
        build:
            context: ./docker/own
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                TIMEZONE: '${APP_TIMEZONE}'
        image: hakase-labs/laravel
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - mynet

#Nginx Service
    nginx:
         image: nginx
         container_name: nginx
         restart: unless-stopped
         tty: true
         environment:
              NGINX_HOST: '${APP_SERVER_NAME}'
              NGINX_HTTP_PORT: '${NGINX_HTTP_PORT}'
              NGINX_HTTPS_PORT: '${NGINX_HTTPS_PORT}'
         ports:
              - '${FORWARD_HTTP_PORT:-80}:80'
              - '${FORWARD_HTTPS_PORT:-443}:443'
         volumes:
              - ./:/var/www/html
              - ./docker/own/nginx/conf.d/default.conf:/etc/nginx/templates/default.conf.template
              - ./docker/own/nginx/ssl/:/etc/nginx/ssl/
         networks:
              - mynet

#MySQL Service
    db:
        image: 'mysql/mysql-server:8.0'
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - mysqldata:/var/lib/mysql/
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - mynet

#Docker Networks
networks:
    mynet:
        driver: bridge

#Volumes
volumes:
    mysqldata:
          driver: local
